name: Cluster Setup
description: Cluster setup for canary test

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

    - name: setup golang
      uses: actions/setup-go@v2
      with:
        go-version: "1.21"

    - name: Setup Minikube
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        tests/scripts/github-action-helper.sh install_minikube_with_none_driver v1.29.2

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh install_deps

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
