name: Cluster Setup
description: Cluster setup for canary test

runs:
  using: "composite"
  steps:
    - name: setup golang
      uses: actions/setup-go@v5
      with:
        go-version: "1.25"

    - name: Setup Minikube
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        tests/scripts/github-action-helper.sh install_minikube_with_none_driver v1.34.0

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh install_deps

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
