version: 2
enable-beta-ecosystems: true
updates:
  # Dependencies listed in go.mod
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      golang-dependencies:
        patterns:
          - "github.com/golang*"
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
      github-dependencies:
        patterns:
          - "github.com*"

  # Dependencies listed in .github/workflows/*.yml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
