apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-attacher-sa
  namespace: rook-ceph-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-external-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-csi-attacher-role
subjects:
  - kind: ServiceAccount
    name: rook-csi-rbd-attacher-sa
    namespace: rook-ceph-system
roleRef:
  kind: ClusterRole
  name: rbd-external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
