#################################################################################################################
# Define the settings for the rook-ceph cluster where only a single mon and mgr are started.
# Other daemons are expected to be set through the Ceph dashboard or by otherwise modifying the cluster crd
# after the initial cluster is created.
# See the cluster CRD documentation for more details: https://rook.io/docs/rook/master/ceph-cluster-crd.html
# For example, to create the cluster:
#   kubectl create -f common.yaml
#   kubectl create -f operator.yaml
#   kubectl create -f cluster-minimal.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.7
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: false
  dashboard:
    enabled: true
    ssl: true
  monitoring:
    enabled: false  # requires Prometheus to be pre-installed
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
