apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rook-operator
  labels:
    operator: rook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-operator
  template:
    metadata:
      labels:
        app: rook-operator
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      containers:
      - name: rook-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - operator
        env:
{{- if not .Values.rbacEnable }}
        - name: RBAC_ENABLED
          value: "false"
{{- end }}
{{- if .Values.agent }}
{{- if .Values.agent.toleration }}
        - name: AGENT_TOLERATION
          value: {{ .Values.agent.toleration }}
{{- end }}
{{- if .Values.agent.tolerationKey }}
        - name: AGENT_TOLERATION_KEY
          value: {{ .Values.agent.tolerationKey }}
{{- end }}
{{- if .Values.agent.flexVolumeDirPath }}
        - name: FLEXVOLUME_DIR_PATH
          value: {{ .Values.agent.flexVolumeDirPath }}
{{- end }}
{{- end }}
        - name: ROOK_LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.mon }}
{{- if .Values.mon.healthCheckInterval }}
        - name: ROOK_MON_HEALTHCHECK_INTERVAL
          value: {{ .Values.mon.healthCheckInterval }}
{{- end }}
{{- if .Values.mon.monOutTimeout }}
        - name: ROOK_MON_OUT_TIMEOUT
          value: {{ .Values.mon.monOutTimeout }}
{{- end }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- if .Values.rbacEnable }}
      serviceAccountName: rook-operator
    {{- end }}
