{{- $root := . -}}
{{- range $filesystem := .Values.cephFileSystems }}
---
kind: CephFilesystemSubVolumeGroup
apiVersion: ceph.rook.io/v1
metadata:
  name: {{ $filesystem.name }}-csi    # lets keep the svg crd name same as `filesystem name + csi` for the default csi svg
  namespace: {{ $root.Release.Namespace }} # namespace:cluster
spec:
  # The name of the subvolume group. If not set, the default is the name of the subvolumeGroup CR.
  name: csi
  # filesystemName is the metadata name of the CephFilesystem CR where the subvolume group will be created
  filesystemName: {{ $filesystem.name }}
  # reference https://docs.ceph.com/en/latest/cephfs/fs-volumes/#pinning-subvolumes-and-subvolume-groups
  # only one out of (export, distributed, random) can be set at a time
  # by default pinning is set with value: distributed=1
  # for disabling default values set (distributed=0)
  pinning:
    distributed: 1 # distributed=<0, 1> (disabled=0)
    # export:      # export=<0-256> (disabled=-1)
    # random:      # random=[0.0, 1.0](disabled=0.0)
---
kind: CephFilesystem
apiVersion: ceph.rook.io/v1
metadata:
  name: {{ $filesystem.name }}
  namespace: {{ $root.Release.Namespace }} # namespace:cluster
spec:
  {{- $filesystem.spec | toYaml | nindent 2 }}
---
{{- if $filesystem.storageClass.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $filesystem.storageClass.name }}
  {{- with $filesystem.storageClass.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ if $filesystem.storageClass.isDefault }}true{{ else }}false{{ end }}"
    {{- with $filesystem.storageClass.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- if $root.Values.csiDriverNamePrefix }}
provisioner: {{ $root.Values.csiDriverNamePrefix }}.cephfs.csi.ceph.com
{{- else }}
provisioner: {{ $root.Values.operatorNamespace }}.cephfs.csi.ceph.com
{{- end }}
parameters:
  fsName: {{ $filesystem.name }}
  pool: {{ $filesystem.name }}-{{ $filesystem.storageClass.pool | default "data0" }}
  clusterID: {{ $root.Release.Namespace }}
  {{- with $filesystem.storageClass.parameters }}
  {{- tpl (. | toYaml) $ | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ $filesystem.storageClass.reclaimPolicy | default "Delete" }}
allowVolumeExpansion: {{ $filesystem.storageClass.allowVolumeExpansion | default "true" }}
volumeBindingMode: {{ $filesystem.storageClass.volumeBindingMode | default "Immediate" }}
{{- with $filesystem.storageClass.mountOptions }}
mountOptions:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
