{{- range .Values.cephObjectStores }}
{{- if dig "ingress" "enabled" false . }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }} # namespace:cluster
  {{- with .ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .ingress.host.name }}
      http:
        paths:
          - path: {{ .ingress.host.path | default "/" }}
            backend:
              service:
                name: rook-ceph-rgw-{{ .name }}
                port:
                  number: {{ .ingress.port | default .spec.gateway.securePort | default .spec.gateway.port }}
            pathType: {{ .ingress.host.pathType | default "Prefix" }}
  {{- with .ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
