{{- if .Values.toolbox.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
{{- $network := .Values.cephClusterSpec.network | default dict -}}
{{- if ($network.provider | default "") | eq "host" }}
      hostNetwork: true
{{- end }}
{{- if .Values.toolbox.priorityClassName }}
      priorityClassName: {{ .Values.toolbox.priorityClassName }}
{{- end }}
      containers:
        - name: rook-ceph-tools
          image: {{ .Values.toolbox.image }}
          command: ["/bin/bash"]
          args: ["-m", "-c", "/usr/local/bin/toolbox.sh"]
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
{{- if .Values.toolbox.resources }}
          resources:
{{- toYaml .Values.toolbox.resources | nindent 12 }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/ceph
              name: ceph-config
            - name: mon-endpoint-volume
              mountPath: /etc/rook
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
                - key: data
                  path: mon-endpoints
        - name: ceph-config
          emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
{{- if .Values.toolbox.tolerations }}
{{ toYaml .Values.toolbox.tolerations | indent 8 }}
{{- end }}
{{- if .Values.toolbox.affinity }}
      affinity:
{{ toYaml .Values.toolbox.affinity | indent 8 }}
{{- end }}
{{- end }}
