{{- if .Values.route.dashboard.host -}}
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: {{ include "clusterName" . }}-dashboard
  namespace: {{ .Release.Namespace }} # namespace:cluster
  {{- with .Values.route.dashboard.labels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- with .Values.route.dashboard.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    - {{ .Values.route.dashboard.host.name | quote }}
  parentRefs:
    {{- .Values.route.dashboard.parentRefs | toYaml | nindent 4 }}
  rules:
    - backendRefs:
        - name: rook-ceph-mgr-dashboard
          {{- if .Values.cephClusterSpec.dashboard.port }}
          port: {{ .Values.cephClusterSpec.dashboard.port }}
          {{- else if .Values.cephClusterSpec.dashboard.ssl }}
          port: 8443
          {{- else }}
          port: 7000
          {{- end }}
      matches:
        - path:
            type: {{ .Values.route.dashboard.host.pathType | default "PathPrefix" }}
            value: {{ .Values.route.dashboard.host.path | default "/" }}
{{- end }}
