{{- if ne .Release.Namespace .Values.operatorNamespace -}}

{{/*
serviceaccounts
*/}}
{{ include "library.cluster.serviceaccounts" . }}

{{/*
clusterrolebindings
*/}}
---
{{ include "library.cluster.clusterrolebindings" . }}

{{- if .Values.pspEnable }}
{{ include "library.cluster.psp.rolebindings" . }}
{{- end }}

{{/*
roles
*/}}
---
{{ include "library.cluster.roles" . }}

{{- if .Values.monitoring.enabled }}
---
{{ include "library.cluster.monitoring.roles" . }}
{{- end }}

{{/*
rolebindings
*/}}
---
{{ include "library.cluster.rolebindings" . }}

{{- if .Values.monitoring.enabled }}
---
{{ include "library.cluster.monitoring.rolebindings" . }}
{{- end }}

{{- end }}
