apiVersion: edgefs.rook.io/v1
kind: S3
metadata:
  name: s301
  namespace: rook-edgefs
spec:
  instances: 1
  #s3type: s3s                    # s3 (default) for path style, s3s for buckets as DNS style
  #serviceType: NodePort          # define ServiceType (default ClusterIP)
  #externalPort: 30303            # define NodePort for HTTP port (default auto)
  #secureExternalPort: 30443      # define NodePort for HTTPS port (default auto)
  #port: 4500                     # HTTP port (default is 9982 or 9983 for s3s)
  #securePort: 4501               # HTTPS port (default is 8443 or 8444 for s3s)
  #sslCertificateRef: ssl-secret
  #placement:
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #      - matchExpressions:
  #        - key: rook-edgefs-nodetype
  #          operator: In
  #          values:
  #          - gateway
  #  tolerations:
  #  - key: rook-edgefs-nodetype
  #    operator: Exists
  #  podAffinity:
  #  podAntiAffinity:
  #resources:
  #  limits:
  #    cpu: "2"
  #    memory: "4Gi"
  #  requests:
  #    cpu: "2"
  #    memory: "4Gi"
  # A key value list of annotations
  # A key value list of annotations
  annotations:
  #  all:
  #    key: value
  #  mgr:
  #  prepare:
  #  target:
