apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-operator
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-operator
  template:
    metadata:
      labels:
        app: rook-ceph-operator
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.annotations }}
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: rook-ceph-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["ceph", "operator"]
        env:
        - name: ROOK_CURRENT_NAMESPACE_ONLY
          value: {{ .Values.currentNamespaceOnly | quote }}
{{- if not .Values.rbacEnable }}
        - name: RBAC_ENABLED
          value: "false"
{{- end }}
{{- if .Values.agent }}
{{- if .Values.agent.toleration }}
        - name: AGENT_TOLERATION
          value: {{ .Values.agent.toleration }}
{{- end }}
{{- if .Values.agent.tolerationKey }}
        - name: AGENT_TOLERATION_KEY
          value: {{ .Values.agent.tolerationKey }}
{{- end }}
{{- if .Values.agent.tolerations }}
        - name: AGENT_TOLERATIONS
          value: {{ toYaml .Values.agent.tolerations | quote }}
{{- end }}
{{- if .Values.agent.nodeAffinity }}
        - name: AGENT_NODE_AFFINITY
          value: {{ .Values.agent.nodeAffinity }}
{{- end }}
{{- if .Values.agent.priorityClassName }}
        - name: AGENT_PRIORITY_CLASS_NAME
          value: {{ .Values.agent.priorityClassName }}
{{- end }}
{{- if .Values.agent.mountSecurityMode }}
        - name: AGENT_MOUNT_SECURITY_MODE
          value: {{ .Values.agent.mountSecurityMode }}
{{- end }}
{{- if .Values.agent.flexVolumeDirPath }}
        - name: FLEXVOLUME_DIR_PATH
          value: {{ .Values.agent.flexVolumeDirPath }}
{{- end }}
{{- if .Values.agent.libModulesDirPath }}
        - name: LIB_MODULES_DIR_PATH
          value: {{ .Values.agent.libModulesDirPath }}
{{- end }}
{{- if .Values.agent.mounts }}
        - name: AGENT_MOUNTS
          value: {{ .Values.agent.mounts }}
{{- end }}
{{- end }}
{{- if .Values.discover }}
{{- if .Values.discover.toleration }}
        - name: DISCOVER_TOLERATION
          value: {{ .Values.discover.toleration }}
{{- end }}
{{- if .Values.discover.tolerationKey }}
        - name: DISCOVER_TOLERATION_KEY
          value: {{ .Values.discover.tolerationKey }}
{{- end }}
{{- if .Values.discover.tolerations }}
        - name: DISCOVER_TOLERATIONS
          value: {{ toYaml .Values.discover.tolerations | quote }}
{{- end }}
{{- if .Values.discover.priorityClassName }}
        - name: DISCOVER_PRIORITY_CLASS_NAME
          value: {{ .Values.discover.priorityClassName }}
{{- end }}
{{- if .Values.discover.nodeAffinity }}
        - name: DISCOVER_AGENT_NODE_AFFINITY
          value: {{ .Values.discover.nodeAffinity }}
{{- end }}
{{- if .Values.discover.podLabels }}
        - name: DISCOVER_AGENT_POD_LABELS
          value: {{ .Values.discover.podLabels }}
{{- end }}
{{- end }}
        - name: ROOK_HOSTPATH_REQUIRES_PRIVILEGED
          value: "{{ .Values.hostpathRequiresPrivileged }}"
        - name: ROOK_LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: ROOK_ENABLE_SELINUX_RELABELING
          value: "{{ .Values.enableSelinuxRelabeling }}"
        - name: ROOK_DISABLE_DEVICE_HOTPLUG
          value: "{{ .Values.disableDeviceHotplug }}"
{{- if .Values.csi }}
        - name: ROOK_CSI_ENABLE_RBD
          value: {{ .Values.csi.enableRbdDriver | quote }}
        - name: ROOK_CSI_ENABLE_CEPHFS
          value: {{ .Values.csi.enableCephfsDriver | quote }}
        - name: CSI_ENABLE_CEPHFS_SNAPSHOTTER
          value: {{ .Values.csi.enableCephfsSnapshotter | quote }}
        - name: CSI_ENABLE_RBD_SNAPSHOTTER
          value: {{ .Values.csi.enableRBDSnapshotter | quote }}
        - name: CSI_PLUGIN_PRIORITY_CLASSNAME
          value: {{ .Values.csi.pluginPriorityClassName | quote }}
        - name: CSI_PROVISIONER_PRIORITY_CLASSNAME
          value: {{ .Values.csi.provisionerPriorityClassName | quote }}
        - name: CSI_ENABLE_OMAP_GENERATOR
          value: {{ .Values.csi.enableOMAPGenerator | quote }}
        - name: CSI_ENABLE_VOLUME_REPLICATION
          value: {{ .Values.csi.volumeReplication.enabled | quote }}
{{- if .Values.csi.enableCSIHostNetwork }}
        - name: CSI_ENABLE_HOST_NETWORK
          value: {{ .Values.csi.enableCSIHostNetwork | quote }}
{{- end }}
{{- if .Values.csi.cephFSPluginUpdateStrategy }}
        - name: CSI_CEPHFS_PLUGIN_UPDATE_STRATEGY
          value: {{ .Values.csi.cephFSPluginUpdateStrategy | quote }}
{{- end }}
{{- if .Values.csi.rbdFSGroupPolicy }}
        - name: CSI_RBD_FSGROUPPOLICY
          value: {{ .Values.csi.rbdFSGroupPolicy | quote }}
{{- end }}
{{- if .Values.csi.cephFSFSGroupPolicy }}
        - name: CSI_CEPHFS_FSGROUPPOLICY
          value: {{ .Values.csi.cephFSFSGroupPolicy | quote }}
{{- end }}
{{- if .Values.csi.rbdPluginUpdateStrategy }}
        - name: CSI_RBD_PLUGIN_UPDATE_STRATEGY
          value: {{ .Values.csi.rbdPluginUpdateStrategy | quote }}
{{- end }}
{{- if .Values.csi.kubeletDirPath }}
        - name: ROOK_CSI_KUBELET_DIR_PATH
          value: {{ .Values.csi.kubeletDirPath | quote }}
{{- end }}
        - name: ROOK_CSI_ENABLE_GRPC_METRICS
          value: {{ .Values.csi.enableGrpcMetrics | quote }}
{{- if .Values.csi.cephcsi }}
{{- if .Values.csi.cephcsi.image }}
        - name: ROOK_CSI_CEPH_IMAGE
          value: {{ .Values.csi.cephcsi.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.registrar }}
{{- if .Values.csi.registrar.image }}
        - name: ROOK_CSI_REGISTRAR_IMAGE
          value: {{ .Values.csi.registrar.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.provisioner }}
{{- if .Values.csi.provisioner.image }}
        - name: ROOK_CSI_PROVISIONER_IMAGE
          value: {{ .Values.csi.provisioner.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.snapshotter }}
{{- if .Values.csi.snapshotter.image }}
        - name: ROOK_CSI_SNAPSHOTTER_IMAGE
          value: {{ .Values.csi.snapshotter.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.attacher }}
{{- if .Values.csi.attacher.image }}
        - name: ROOK_CSI_ATTACHER_IMAGE
          value: {{ .Values.csi.attacher.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.resizer }}
{{- if .Values.csi.resizer.image }}
        - name: ROOK_CSI_RESIZER_IMAGE
          value: {{ .Values.csi.resizer.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.volumeReplication }}
{{- if .Values.csi.volumeReplication.image }}
        - name: CSI_VOLUME_REPLICATION_IMAGE
          value: {{ .Values.csi.volumeReplication.image | quote }}
{{- end }}
{{- end }}
{{- if .Values.csi.cephfsPodLabels }}
        - name: ROOK_CSI_CEPHFS_POD_LABELS
          value: {{ .Values.csi.cephfsPodLabels | quote }}
{{- end }}
{{- if .Values.csi.rbdPodLabels }}
        - name: ROOK_CSI_RBD_POD_LABELS
          value: {{ .Values.csi.rbdPodLabels | quote }}
{{- end }}
{{- if .Values.csi.provisionerTolerations }}
        - name: CSI_PROVISIONER_TOLERATIONS
          value: {{ toYaml .Values.csi.provisionerTolerations | quote }}
{{- end }}
{{- if .Values.csi.provisionerNodeAffinity }}
        - name: CSI_PROVISIONER_NODE_AFFINITY
          value: {{ .Values.csi.provisionerNodeAffinity }}
{{- end }}
{{- if .Values.csi.rbdProvisionerTolerations }}
        - name: CSI_RBD_PROVISIONER_TOLERATIONS
          value: {{ toYaml .Values.csi.rbdProvisionerTolerations | quote }}
{{- end }}
{{- if .Values.csi.rbdProvisionerNodeAffinity }}
        - name: CSI_RBD_PROVISIONER_NODE_AFFINITY
          value: {{ .Values.csi.rbdProvisionerNodeAffinity }}
{{- end }}
{{- if .Values.csi.cephFSProvisionerTolerations }}
        - name: CSI_CEPHFS_PROVISIONER_TOLERATIONS
          value: {{ toYaml .Values.csi.cephFSProvisionerTolerations | quote }}
{{- end }}
{{- if .Values.csi.cephFSProvisionerNodeAffinity }}
        - name: CSI_CEPHFS_PROVISIONER_NODE_AFFINITY
          value: {{ .Values.csi.cephFSProvisionerNodeAffinity }}
{{- end }}
{{- if .Values.csi.allowUnsupportedVersion }}
        - name: ROOK_CSI_ALLOW_UNSUPPORTED_VERSION
          value: {{ .Values.csi.allowUnsupportedVersion | quote }}
{{- end }}
{{- if .Values.csi.pluginTolerations }}
        - name: CSI_PLUGIN_TOLERATIONS
          value: {{ toYaml .Values.csi.pluginTolerations | quote }}
{{- end }}
{{- if .Values.csi.pluginNodeAffinity }}
        - name: CSI_PLUGIN_NODE_AFFINITY
          value: {{ .Values.csi.pluginNodeAffinity }}
{{- end }}
{{- if .Values.csi.rbdPluginTolerations }}
        - name: CSI_RBD_PLUGIN_TOLERATIONS
          value: {{ toYaml .Values.csi.rbdPluginTolerations | quote }}
{{- end }}
{{- if .Values.csi.rbdPluginNodeAffinity }}
        - name: CSI_RBD_PLUGIN_NODE_AFFINITY
          value: {{ .Values.csi.rbdPluginNodeAffinity }}
{{- end }}
{{- if .Values.csi.cephFSPluginTolerations }}
        - name: CSI_CEPHFS_PLUGIN_TOLERATIONS
          value: {{ toYaml .Values.csi.cephFSPluginTolerations | quote }}
{{- end }}
{{- if .Values.csi.cephFSPluginNodeAffinity }}
        - name: CSI_CEPHFS_PLUGIN_NODE_AFFINITY
          value: {{ .Values.csi.cephFSPluginNodeAffinity }}
{{- end }}
{{- if .Values.csi.cephfsGrpcMetricsPort }}
        - name: CSI_CEPHFS_GRPC_METRICS_PORT
          value: {{ .Values.csi.cephfsGrpcMetricsPort | quote }}
{{- end }}
{{- if .Values.csi.cephfsLivenessMetricsPort }}
        - name: CSI_CEPHFS_LIVENESS_METRICS_PORT
          value: {{ .Values.csi.cephfsLivenessMetricsPort | quote }}
{{- end }}
{{- if .Values.csi.rbdGrpcMetricsPort }}
        - name: CSI_RBD_GRPC_METRICS_PORT
          value: {{ .Values.csi.rbdGrpcMetricsPort | quote }}
{{- end }}
{{- if .Values.csi.rbdLivenessMetricsPort }}
        - name: CSI_RBD_LIVENESS_METRICS_PORT
          value: {{ .Values.csi.rbdLivenessMetricsPort | quote }}
{{- end }}
{{- if .Values.csi.forceCephFSKernelClient }}
        - name: CSI_FORCE_CEPHFS_KERNEL_CLIENT
          value: {{ .Values.csi.forceCephFSKernelClient | quote }}
{{- end }}
{{- if .Values.csi.logLevel }}
        - name: CSI_LOG_LEVEL
          value: {{ .Values.csi.logLevel | quote }}
{{- end }}
{{- if .Values.csi.csiRBDProvisionerResource }}
        - name: CSI_RBD_PROVISIONER_RESOURCE
          value: {{ .Values.csi.csiRBDProvisionerResource | quote }}
{{- end }}
{{- if .Values.csi.csiRBDPluginResource }}
        - name: CSI_RBD_PLUGIN_RESOURCE
          value: {{ .Values.csi.csiRBDPluginResource | quote }}
{{- end }}
{{- if .Values.csi.csiCephFSProvisionerResource }}
        - name: CSI_CEPHFS_PROVISIONER_RESOURCE
          value: {{ .Values.csi.csiCephFSProvisionerResource | quote }}
{{- end }}
{{- if .Values.csi.csiCephFSPluginResource }}
        - name: CSI_CEPHFS_PLUGIN_RESOURCE
          value: {{ .Values.csi.csiCephFSPluginResource | quote }}
{{- end }}
{{- end }}
        - name: ROOK_ENABLE_FLEX_DRIVER
          value: "{{ .Values.enableFlexDriver }}"
        - name: ROOK_ENABLE_DISCOVERY_DAEMON
          value: "{{ .Values.enableDiscoveryDaemon }}"
        - name: ROOK_OBC_WATCH_OPERATOR_NAMESPACE
          value: "{{ .Values.enableOBCWatchOperatorNamespace }}"

        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.admissionController }}
{{- if .Values.admissionController.tolerations }}
        - name: ADMISSION_CONTROLLER_TOLERATIONS
          value: {{ toYaml .Values.admissionController.tolerations | quote }}
{{- end }}
{{- if .Values.admissionController.nodeAffinity }}
        - name: ADMISSION_CONTROLLER_NODE_AFFINITY
          value: {{ .Values.admissionController.nodeAffinity }}
{{- end }}
{{- end }}
{{- if .Values.unreachableNodeTolerationSeconds }}
        - name: ROOK_UNREACHABLE_NODE_TOLERATION_SECONDS
          value: {{ .Values.unreachableNodeTolerationSeconds | quote }}
{{- end }}
{{- if .Values.allowMultipleFilesystems }}
        - name: ROOK_ALLOW_MULTIPLE_FILESYSTEMS
          value: {{ .Values.allowMultipleFilesystems | quote }}
{{- end }}
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
{{- if .Values.useOperatorHostNetwork }}
      hostNetwork: true
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.rbacEnable }}
      serviceAccountName: rook-ceph-system
{{- end }}
