# Service account for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-system
  namespace:  {{  .Release.Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ template "imagePullSecrets" . }}
---
# Service account for the Ceph OSDs. Must exist and cannot be renamed.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
  namespace:  {{  .Release.Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ template "imagePullSecrets" . }}
---
# Service account for the Ceph Mgr. Must exist and cannot be renamed.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
  namespace:  {{  .Release.Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ template "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
  namespace:  {{  .Release.Namespace }}
  labels:
    operator: rook
    storage-backend: ceph
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ template "imagePullSecrets" . }}
---
# Service account for the cephfs csi driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-plugin-sa
  namespace:  {{  .Release.Namespace }}
{{ template "imagePullSecrets" . }}
---
# Service account for the cephfs csi provisioner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-cephfs-provisioner-sa
  namespace:  {{  .Release.Namespace }}
{{ template "imagePullSecrets" . }}
---
# Service account for the rbd csi driver
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-plugin-sa
  namespace:  {{  .Release.Namespace }}
{{ template "imagePullSecrets" . }}
---
# Service account for the rbd csi provisioner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-csi-rbd-provisioner-sa
  namespace:  {{  .Release.Namespace }}
{{ template "imagePullSecrets" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-admission-controller
  namespace: {{  .Release.Namespace }}
---