{{- if .Values.cluster.enabled -}}
{{- if .Values.rbacEnable }}
{{- if .Values.pspEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: rook-operator-psp-users
  namespace: {{ .Release.Namespace }}
  labels:
    operator: rook
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rook-operator-psp-user
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: rook-ceph-osd
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
