name: setup cluster resources
description: Setup cluster resources for canary/integration tests
inputs:
  kubernetes-version:
    description: kubernetes version to use for the workflow
    required: true

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true # removes old golang version but saves ~6GB
        large-packages: false # takes a long time to run b/c package mgr
        android: false # takes a long time to run b/c package mgr
        dotnet: false # takes a long time to run b/c package mgr
        haskell: false # takes a long time to run b/c package mgr

    - name: setup golang
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: "1.24"

    - name: Setup Minikube
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        tests/scripts/github-action-helper.sh install_minikube_with_none_driver ${{ inputs.kubernetes-version }}

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh install_deps

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    # This step is required for all the integration tests except the canary tests
    - name: use local disk
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh use_local_disk_for_integration_test

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
