name: setup cluster resources
description: Setup cluster resources for canary/integration tests
inputs:
  kubernetes-version:
    description: kubernetes version to use for the workflow
    required: true

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true # removes old golang version but saves ~6GB
        large-packages: false # takes a long time to run b/c package mgr
        android: false # takes a long time to run b/c package mgr
        dotnet: false # takes a long time to run b/c package mgr
        haskell: false # takes a long time to run b/c package mgr

    - name: setup golang
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: "1.25"

    - name: Install cri-dockerd
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: |
        ARCH=$(go env GOARCH)
        curl -LO https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.21/cri-dockerd_0.3.21.3-0.ubuntu-focal_${ARCH}.deb
        sudo dpkg -i cri-dockerd_0.3.21.3-0.ubuntu-focal_${ARCH}.deb
        rm -f cri-dockerd_0.3.21.3-0.ubuntu-focal_${ARCH}.deb

    - name: Setup Minikube
      uses: medyagh/setup-minikube@latest
      with:
        # lock minikube version to ensure release branch CI doesn't fail when latest minikube no
        # longer supports older k8s version we lock to
        minikube-version: "1.38.0"
        kubernetes-version: ${{ inputs.kubernetes-version }}
        driver: none
        container-runtime: docker
        memory: 6g
        cpus: 2
        addons: ingress
        cni: calico

    - name: install deps
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh install_deps

    - name: print k8s cluster status
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

    # This step is required for all the integration tests except the canary tests
    - name: use local disk
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh use_local_disk_for_integration_test

    - name: build rook
      shell: bash --noprofile --norc -eo pipefail -x {0}
      run: tests/scripts/github-action-helper.sh build_rook
