{{- if .Values.ingress.dashboard.host }}
---
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ template "clusterName" . }}-dashboard
  {{- if .Values.ingress.dashboard.annotations }}
  annotations: {{- toYaml .Values.ingress.dashboard.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.dashboard.host.name }}
      http:
        paths:
          - path: {{ .Values.ingress.dashboard.host.path | default "/" }}
            backend:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  name: http-dashboard
            pathType: Prefix
{{- else }}
              serviceName: rook-ceph-mgr-dashboard
              servicePort: http-dashboard
{{- end }}
  {{- if .Values.ingress.dashboard.tls }}
  tls: {{- toYaml .Values.ingress.dashboard.tls | nindent 4 }}
  {{- end }}
{{- end }}
