apiVersion: rook.io/v1alpha1
kind: Rookpool
metadata:
  name: replicapool
  namespace: rook
spec:
  replication:
    size: 1
  # For an erasure-coded pool, comment out the replication count above and uncomment the following settings.
  # Make sure you have enough OSDs to support the replica count or erasure code chunks.
  #erasureCode:
  #  codingChunks: 2
  #  dataChunks: 2
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
   name: rook-block
   namespace: rook
provisioner: rook.io/block
parameters:
    pool: replicapool
    # Specify the Rook cluster from which to create volumes. If not specified, it will use `rook` as the namespace and name of the cluster.
    # clusterName: rook
    # clusterNamespace: rook
