apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: replicapool
  namespace: rook
spec:
  # For a pool based on raw copies, specify the number of copies. A size of 1 indicates no redundancy.
  replication:
    size: 1
  # For an erasure-coded pool, comment out the replication size above and uncomment the following settings.
  # Make sure you have enough OSDs to support the replica size or sum of the erasure coding and data chunks.
  #erasureCode:
  #  codingChunks: 2
  #  dataChunks: 2
  