apiVersion: v1
kind: Pod
metadata:
  name: rook-client
  namespace: rook
spec:
  containers:
  - name: rook-client
    image: quay.io/rook/rook:master-latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "36500d"]
    securityContext:
      privileged: true
    volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: libmodules
  volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: libmodules
        hostPath:
          path: /lib/modules