apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rook-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rook-operator
    spec:
      containers:
      - name: rook-operator
        image: quay.io/rook/rookd:master-latest
        args: ["operator"]
        env:
        - name: ROOKD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOKD_REPO_PREFIX
          value: quay.io/rook

