name: Cluster Setup
description: Cluster setup for integration test
inputs:
  kubernetes-version:
    description: kubernetes version to use for the workflow
    required: true
  github-token:
    description: GITHUB_TOKEN from the calling workflow
    required: true

runs:
  using: "composite"
  steps:
  - name: setup golang
    uses: actions/setup-go@v2
    with:
      go-version: 1.17

  - name: setup minikube
    uses: manusa/actions-setup-minikube@v2.4.2
    with:
      minikube version: "v1.24.0"
      kubernetes version: ${{ inputs.kubernetes-version }}
      start args: --memory 6g --cpus=2 --addons ingress
      github token: ${{ inputs.github-token }}

  - name: print k8s cluster status
    shell: bash --noprofile --norc -eo pipefail -x {0}
    run: tests/scripts/github-action-helper.sh print_k8s_cluster_status

  - name: use local disk
    shell: bash --noprofile --norc -eo pipefail -x {0}
    run: tests/scripts/github-action-helper.sh use_local_disk_for_integration_test

  - name: build rook
    shell: bash --noprofile --norc -eo pipefail -x {0}
    run: tests/scripts/github-action-helper.sh build_rook
