#################################################################################################################
# Create a storage class with a pool for a test environment. Only a single OSD is required in this example.
#  kubectl create -f storageclass-test.yaml
#################################################################################################################

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: replicapool
  namespace: rook-ceph
spec:
  replicated:
    size: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
provisioner: ceph.rook.io/block
# Works for Kubernetes 1.14+
allowVolumeExpansion: true
parameters:
  blockPool: replicapool
  clusterNamespace: rook-ceph
  fstype: xfs
