apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rook-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: rook-operator
    spec:
      containers:
      - name: rook-operator
        image: rook/rook:v0.5.0
        args: ["operator"]
        env:
        - name: ROOK_REPO_PREFIX
          value: rook
