apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr
  namespace: rook
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
      - rook
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s
