# This workflow is based on https://github.com/dependabot/dependabot-actions-workflow

name: Build Dependabot Bundler PR
on:
  push:
    branches:
      - "dependabot/go_modules/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: run mod check
        run: GOPATH=$(go env GOPATH) make -j $(nproc) mod.check

      - run: mkdir ./dependabot-pr

      - name: Save branch ref
        run: echo ${{ github.ref }} | sed 's/refs\/heads\///' > ./dependabot-pr/BRANCH_REF

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      # NOTE: Prefixing/appending commit messages with `[dependabot skip]` allows
      # dependabot to rebase/update the pull request, force-pushing over any changes

      - name: Commit and copy changes
        run: |
          if [[ $(git status | grep -E '(go.mod|go.sum)') ]]; then
            git add go.mod go.sum pkg/apis/go.mod pkg/apis/go.sum
            git commit -m "[dependabot skip] Update Golang Modules"
            git format-patch -n HEAD^ --binary --stdout > ./dependabot-pr/changes.patch
          else
            echo "Golang Modules were not changed"
          fi

      # NOTE: Use actions/upload-artifact instead of actions/cache as the
      # workflow triggered on the default branch doesn't have access to caches
      # created on feature branches

      - uses: actions/upload-artifact@v3
        with:
          name: dependabot-pr
          path: dependabot-pr/
