name: Codespell
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: .git,*.png,*.jpg,*.svg,*.sum
          # aks: Amazon Kubernetes Service
          # keyserver: flag to apt-key
          # atleast: codespell wants to flag any 'AtLeast' method
          # ser, ist: MIME types in pkg/operator/ceph/object/mime.go
          # ba: daemon ID test in pkg/operator/k8sutil/name_test.go
          # iam: Identity and Access Management, e.g., AWS IAM
          # te: udev persistent naming test in pkg/daemon/ceph/osd/daemon_test.go
          # parm: modinfo parameter
          # assigment: inherited from K8s TopologySpreadConstraints dependency
          ignore_words_list: aks,keyserver,atleast,ser,ist,ba,iam,te,parm,assigment
          check_filenames: true
          check_hidden: true
