name: CRDs gen
on:
  pull_request:

jobs:
  crds-gen:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: checkout
      uses: actions/checkout@v2

    - name: copy working directory to GOPATH
      run: sudo mkdir -p /home/runner/go/src/github.com && sudo cp -a /home/runner/work/rook /home/runner/go/src/github.com/

    - name: run crds-gen
      working-directory: /home/runner/go/src/github.com/rook/rook
      run: GOPATH=$(go env GOPATH) make crds

    - name: validate crds-gen
      working-directory: /home/runner/go/src/github.com/rook/rook
      run: tests/scripts/validate_modified_files.sh crd
